name: blockInfo

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  block_update:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script 
        env: 
          INFURA_URL: ${{ secrets.INFURA_URL }}
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "dsanurag520.com"
          git config --local user.name "Anurag-gg"
          git add -A
          git commit -m "update data" -a
          git push
          